version: '3.8'

services:
  cli:
    build:
      context: ..
      dockerfile: docker/dockerfile
    volumes:
      - ../:/app
    restart: always
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=localhost"
      PHP_IDE_KEY: "PHPSTORM"

